# Generated by Django 5.2.17 on 2026-09-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firmware", "0001_initial"),
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildorder",
            name="firmware_releases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which firmware versions go on these boards. Recorded so every build is traceable.",
                related_name="builds",
                to="firmware.firmwarerelease",
                verbose_name="Firmware to flash",
            ),
        ),
    ]
