# Generated by Django 5.2.17 on 2026-09-26 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def existing_builds(apps, schema_editor):
    """Builds made before 1.3: no manufacturer meant in house; stage follows status."""
    BuildOrder = apps.get_model("production", "BuildOrder")
    for b in BuildOrder.objects.all():
        b.assembly = "fab" if b.manufacturer_id else "house"
        b.stage = {"planned": "planned", "in_progress": "testing", "completed": "done", "cancelled": "planned"}.get(b.status, "planned")
        b.save(update_fields=["assembly", "stage"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_bom_fitted_by"),
        ("production", "0002_buildorder_firmware_releases"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="buildorder",
            name="assembly",
            field=models.CharField(
                choices=[
                    (
                        "fab",
                        "Assembled by JLCPCB, Seeed or another assembly house, then finished in house",
                    ),
                    ("house", "Assembled completely in house"),
                ],
                default="fab",
                max_length=8,
                verbose_name="How are the boards assembled?",
            ),
        ),
        migrations.AddField(
            model_name="buildorder",
            name="fab_order_ref",
            field=models.CharField(
                blank=True,
                help_text="e.g. the JLCPCB order number (SO…), for tracking and re-orders.",
                max_length=80,
                verbose_name="Assembly order number",
            ),
        ),
        migrations.AddField(
            model_name="buildorder",
            name="fab_ordered_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buildorder",
            name="fab_tracking",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Shipping tracking"
            ),
        ),
        migrations.AddField(
            model_name="buildorder",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buildorder",
            name="received_qty",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Boards received from the assembly house.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="buildorder",
            name="stage",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("at_fab", "At the assembly house"),
                    ("finishing", "Finishing in house"),
                    ("testing", "Test & flash"),
                    ("done", "Done"),
                ],
                default="planned",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="BuildStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("detail", models.CharField(blank=True, max_length=200)),
                (
                    "per_board",
                    models.PositiveIntegerField(default=1, help_text="Parts per board"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("done_qty", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bom_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.bomline",
                    ),
                ),
                (
                    "build",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="production.buildorder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(existing_builds, migrations.RunPython.noop),
]
