# Generated by Django 5.2.17 on 2026-09-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_fab_assembly_and_finishing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ordered", "Ordered"),
                    ("partial", "Partly received"),
                    ("received", "Received"),
                    ("closed", "Closed short"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
