# Generated by Django 5.2.17 on 2026-09-25 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0002_move_task_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="blocked_reason",
            field=models.CharField(
                blank=True,
                help_text="If this task can't move forward, say why (e.g. waiting for parts, waiting on PWR-3). Leave empty when not blocked.",
                max_length=200,
                verbose_name="Blocked by",
            ),
        ),
        migrations.CreateModel(
            name="RevisionCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="projects.revision",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.DeleteModel(
            name="TaskAttachment",
        ),
    ]
