# Generated by Django 5.2.17 on 2026-09-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_task_blocked_reason_revisioncheck_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="revision",
            options={
                "ordering": ["project", "board__order", "board_id", "-created_at"]
            },
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Power board, Control board, Front panel",
                        max_length=80,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Optional short code or part number printed on the PCB, e.g. PB or PCB-1001.",
                        max_length=12,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("main", "Main / controller board"),
                            ("power", "Power board"),
                            ("control", "Control board"),
                            ("peripheral", "Peripheral / I/O board"),
                            ("interface", "Interface / connector board"),
                            ("display", "Display / user interface board"),
                            ("sensor", "Sensor board"),
                            ("rf", "RF / wireless module"),
                            ("other", "Other"),
                        ],
                        default="main",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What this board does and how it connects to the others.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "order", "id"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddField(
            model_name="revision",
            name="board",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="projects.board",
            ),
        ),
    ]
