# Generated by Django 5.2.17 on 2026-09-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Also send my notifications by email (when the administrator has set up email).",
            ),
        ),
    ]
