# Generated by Django 5.2.17 on 2026-09-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_email_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_last_step",
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
