# Generated by Django 5.2.17 on 2026-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_mfa_last_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_failed_login",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_failures",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
