# Generated by Django 5.2.17 on 2026-09-26 07:15

import apps.design.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_task_blocked_reason_revisioncheck_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DesignFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gerber", "Gerbers"),
                            ("drill", "Drill files"),
                            ("schematic", "Schematic"),
                            ("pcb", "PCB layout"),
                            ("project", "Design project"),
                            ("bom", "BOM"),
                            ("pnp", "Pick and place (CPL)"),
                            ("assembly", "Assembly drawings"),
                            ("model", "3D model"),
                            ("fab", "Fabrication notes"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "file",
                    models.FileField(
                        max_length=400, upload_to=apps.design.models.design_path
                    ),
                ),
                ("size", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(max_length=64)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_files",
                        to="projects.revision",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name", "-version"],
                "indexes": [
                    models.Index(
                        fields=["revision", "name", "is_current"],
                        name="design_desi_revisio_b68c64_idx",
                    )
                ],
            },
        ),
    ]
