# Generated by Django 5.2.17 on 2026-09-29 07:03

import apps.cad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("design", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="designfile",
            name="mesh",
            field=models.FileField(
                blank=True, max_length=300, upload_to=apps.cad.models.mesh_path
            ),
        ),
        migrations.AddField(
            model_name="designfile",
            name="mesh_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="designfile",
            name="mesh_message",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="designfile",
            name="mesh_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not a 3D file"),
                    ("pending", "Waiting to be prepared"),
                    ("converting", "Being prepared"),
                    ("ready", "Ready"),
                    ("failed", "Couldn't be shown"),
                    ("native", "Native CAD file"),
                ],
                default="",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="designfile",
            name="thumb",
            field=models.FileField(
                blank=True, max_length=300, upload_to=apps.cad.models.mesh_path
            ),
        ),
    ]
