# Generated by Django 5.2.17 on 2026-09-25 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_id", models.CharField(max_length=64, unique=True)),
                ("event", models.CharField(max_length=40)),
                ("repository", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(max_length=20)),
                ("message", models.CharField(blank=True, max_length=300)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=300)),
                ("url", models.URLField()),
                ("author_login", models.CharField(blank=True, max_length=39)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("draft", "Draft"),
                            ("merged", "Merged"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("branch", models.CharField(blank=True, max_length=255)),
                ("head_sha", models.CharField(blank=True, max_length=40)),
                (
                    "checks",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("pending", "Running"),
                            ("success", "Passed"),
                            ("failure", "Failed"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("review_state", models.CharField(blank=True, max_length=30)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True, related_name="pull_requests", to="projects.task"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("project", "number")},
            },
        ),
    ]
