# Generated by Django 5.2.17 on 2026-09-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookdelivery",
            name="body_sha256",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
