# Generated by Django 5.2.17 on 2026-09-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeshJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=60)),
                ("object_id", models.PositiveBigIntegerField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("model", "object_id")},
            },
        ),
    ]
