# Generated by Django 5.2.17 on 2026-09-29 07:04

import apps.cad.models
import apps.mechanical.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0005_board_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MechanicalPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Main enclosure, Top cover, Battery bracket",
                        max_length=120,
                    ),
                ),
                (
                    "part_number",
                    models.CharField(
                        blank=True,
                        help_text="Optional drawing or part number, e.g. MEC-1002",
                        max_length=60,
                    ),
                ),
                (
                    "revision",
                    models.CharField(
                        default="A",
                        help_text="Revision letter or number, e.g. A, B, 02",
                        max_length=12,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("enclosure", "Enclosure / housing"),
                            ("cover", "Lid / cover"),
                            ("bracket", "Bracket / mount"),
                            ("panel", "Front panel / bezel"),
                            ("button", "Button / knob / keycap"),
                            ("lightpipe", "Light pipe / window"),
                            ("seal", "Gasket / seal"),
                            ("heatsink", "Heatsink / thermal"),
                            ("standoff", "Standoff / spacer"),
                            ("other", "Other"),
                        ],
                        default="enclosure",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("concept", "Concept"),
                            ("prototype", "Prototype"),
                            ("released", "Released for production"),
                            ("obsolete", "Obsolete"),
                        ],
                        default="concept",
                        max_length=20,
                    ),
                ),
                (
                    "process",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fdm", "3D print (FDM)"),
                            ("sla", "3D print (resin / SLA)"),
                            ("sls", "3D print (SLS / MJF)"),
                            ("mould", "Injection moulding"),
                            ("cnc", "CNC machining"),
                            ("sheet", "Sheet metal"),
                            ("laser", "Laser / waterjet cut"),
                            ("extrusion", "Extrusion"),
                            ("cast", "Casting"),
                            ("cots", "Bought in (off the shelf)"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Manufacturing process",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="e.g. PETG, ABS, PC-ABS, Aluminium 6061",
                        max_length=80,
                    ),
                ),
                (
                    "finish",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Matte black, anodised, bead-blasted",
                        max_length=80,
                        verbose_name="Colour / finish",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantity per product"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        help_text="Who makes it, e.g. JLC3DP, PCBWay, in house",
                        max_length=120,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "boards",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The boards this part holds or mounts.",
                        related_name="housings",
                        to="projects.board",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mechanical_parts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "kind", "name"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="MechanicalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mesh",
                    models.FileField(
                        blank=True, max_length=300, upload_to=apps.cad.models.mesh_path
                    ),
                ),
                (
                    "thumb",
                    models.FileField(
                        blank=True, max_length=300, upload_to=apps.cad.models.mesh_path
                    ),
                ),
                (
                    "mesh_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Not a 3D file"),
                            ("pending", "Waiting to be prepared"),
                            ("converting", "Being prepared"),
                            ("ready", "Ready"),
                            ("failed", "Couldn't be shown"),
                            ("native", "Native CAD file"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("mesh_message", models.CharField(blank=True, max_length=300)),
                ("mesh_info", models.JSONField(blank=True, default=dict)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("model", "3D model"),
                            ("source", "CAD source"),
                            ("drawing", "Drawing"),
                            ("print", "Print / manufacturing file"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "file",
                    models.FileField(
                        max_length=400, upload_to=apps.mechanical.models.mech_path
                    ),
                ),
                ("size", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(max_length=64)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="mechanical.mechanicalpart",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "name", "-version"],
                "indexes": [
                    models.Index(
                        fields=["part", "name", "is_current"],
                        name="mechanical__part_id_a18742_idx",
                    )
                ],
            },
        ),
    ]
