# Generated by Django 5.2.17 on 2026-09-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(default="Workbench", max_length=80)),
                (
                    "site_url",
                    models.URLField(
                        blank=True,
                        help_text="The address people use to open Workbench, e.g. https://workbench.example.com. Used in sign-in links, emails and the GitHub webhook address.",
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(
                        default="UTC",
                        help_text="Used to schedule nightly backups.",
                        max_length=64,
                    ),
                ),
                (
                    "_github_secret",
                    models.TextField(blank=True, db_column="github_secret"),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Send notifications and sign-in links by email.",
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(
                        blank=True,
                        help_text="e.g. smtp.gmail.com or smtp.office365.com",
                        max_length=200,
                        verbose_name="SMTP server",
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(default=587, verbose_name="SMTP port"),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SMTP username"
                    ),
                ),
                (
                    "_smtp_password",
                    models.TextField(blank=True, db_column="smtp_password"),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(default=True, verbose_name="Use STARTTLS"),
                ),
                (
                    "email_from",
                    models.EmailField(
                        blank=True,
                        help_text="e.g. workbench@yourcompany.com",
                        max_length=254,
                        verbose_name="Send emails from",
                    ),
                ),
                (
                    "backup_enabled",
                    models.BooleanField(default=True, verbose_name="Nightly backups"),
                ),
                (
                    "backup_hour",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Backup time (hour, 0–23)"
                    ),
                ),
                (
                    "backup_keep",
                    models.PositiveSmallIntegerField(
                        default=14, verbose_name="Backups to keep"
                    ),
                ),
                (
                    "trash_days",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Empty trash after (days)"
                    ),
                ),
                (
                    "max_upload_mb",
                    models.PositiveIntegerField(
                        default=200, verbose_name="Largest upload (MB)"
                    ),
                ),
                ("setup_completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_backup_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "site settings",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="emailed",
            field=models.BooleanField(default=False),
        ),
    ]
