# Generated by Django 5.2.17 on 2026-09-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_notification_emailed"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.FileField(
                blank=True,
                help_text="Shown on light backgrounds (sign-in page, printouts).",
                max_length=200,
                upload_to="branding/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_dark",
            field=models.FileField(
                blank=True,
                help_text="Optional version for the dark menu bar, e.g. a white logo.",
                max_length=200,
                upload_to="branding/",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
