# Generated by Django 5.2.17 on 2026-09-26 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_exportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.JSONField(blank=True, default=dict)),
                ("draft", models.JSONField(blank=True, default=dict)),
                ("previous", models.JSONField(blank=True, default=dict)),
                ("locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("draft_tested_at", models.DateTimeField(blank=True, null=True)),
                ("draft_test_ok", models.BooleanField(default=False)),
                ("draft_test_message", models.CharField(blank=True, max_length=300)),
                ("rev", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "storage settings",
            },
        ),
        migrations.CreateModel(
            name="StorageMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.JSONField(default=dict)),
                ("target", models.JSONField(default=dict)),
                ("lock_after", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting to start"),
                            ("running", "Copying files"),
                            ("done", "Finished"),
                            ("failed", "Stopped"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("done_count", models.PositiveIntegerField(default=0)),
                ("copied", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                ("bytes_copied", models.BigIntegerField(default=0)),
                ("failures", models.JSONField(blank=True, default=list)),
                ("message", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
