# Generated by Django 5.2.17 on 2026-09-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_storage_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="last_backup_error",
            field=models.CharField(blank=True, editable=False, max_length=300),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="last_housekeeping_on",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="last_nightly_attempt_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
