# Generated by Django 5.2.17 on 2026-09-25 01:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ipn",
                    models.CharField(
                        blank=True,
                        help_text="Your internal part number, e.g. RES-0001. Leave blank to generate one.",
                        max_length=40,
                        unique=True,
                        verbose_name="Part number",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("resistor", "Resistor"),
                            ("capacitor", "Capacitor"),
                            ("inductor", "Inductor"),
                            ("diode", "Diode / LED"),
                            ("transistor", "Transistor"),
                            ("ic", "IC / microcontroller"),
                            ("connector", "Connector"),
                            ("module", "Module"),
                            ("pcb", "Bare PCB"),
                            ("mechanical", "Mechanical / hardware"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, help_text="e.g. 10k, 100nF, 3.3V", max_length=60
                    ),
                ),
                (
                    "footprint",
                    models.CharField(
                        blank=True,
                        help_text="KiCad footprint, e.g. Resistor_SMD:R_0603_1608Metric",
                        max_length=120,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=120)),
                (
                    "mpn",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=120,
                        verbose_name="Manufacturer part number",
                    ),
                ),
                ("datasheet_url", models.URLField(blank=True)),
                (
                    "supplier_sku",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Supplier SKU"
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("stock", models.IntegerField(default=0)),
                (
                    "min_stock",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="You'll see a warning when stock falls below this.",
                        verbose_name="Reorder level",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Where it's stored, e.g. Shelf B / Bin 12",
                        max_length=80,
                    ),
                ),
                (
                    "lifecycle",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("nrnd", "Not recommended for new designs"),
                            ("obsolete", "Obsolete"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["ipn"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("distributor", "Component distributor"),
                            ("pcb", "PCB fabricator"),
                            ("assembly", "Assembly house / contract manufacturer"),
                            ("other", "Other"),
                        ],
                        default="distributor",
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("country", models.CharField(blank=True, max_length=60)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        default=14, help_text="Typical days from order to delivery."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField()),
                ("balance_after", models.IntegerField(default=0)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("received", "Received from purchase order"),
                            ("build", "Used in a build"),
                            ("adjust", "Manual adjustment / stock count"),
                            ("return", "Returned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.part",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="part",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parts",
                to="inventory.supplier",
            ),
        ),
        migrations.CreateModel(
            name="BomLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "references",
                    models.TextField(
                        blank=True,
                        help_text="Schematic reference designators, e.g. R1, R2, R5",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="How many are used on one board."
                    ),
                ),
                (
                    "dnp",
                    models.BooleanField(default=False, verbose_name="Do not populate"),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_lines",
                        to="projects.revision",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_lines",
                        to="inventory.part",
                    ),
                ),
            ],
            options={
                "ordering": ["part__ipn"],
                "unique_together": {("revision", "part")},
            },
        ),
    ]
