# Generated by Django 5.2.17 on 2026-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomline",
            name="fitted_by",
            field=models.CharField(
                choices=[("fab", "Assembly house"), ("house", "In house")],
                default="fab",
                help_text="Who solders this part when boards are assembled by JLCPCB, Seeed or another assembly house. “In house” parts are left off the assembler's files and fitted by your team afterwards.",
                max_length=8,
                verbose_name="Fitted by",
            ),
        ),
    ]
