# Generated by Django 5.2.17 on 2026-09-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_bom_fitted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="currency",
            field=models.CharField(
                default="USD",
                help_text="The currency this supplier quotes in. Orders are priced in it.",
                max_length=3,
            ),
        ),
    ]
