# Generated by Django 5.2.17 on 2026-09-25 23:14

import apps.firmware.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_task_blocked_reason_revisioncheck_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Firmware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Main application, Bootloader, Radio co-processor",
                        max_length=80,
                    ),
                ),
                ("slug", models.SlugField(max_length=80)),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="e.g. STM32G031K8, ESP32-S3",
                        max_length=80,
                        verbose_name="Target / MCU",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "github_repo",
                    models.CharField(
                        blank=True,
                        help_text="owner/name. Leave empty if it's the project's repository.",
                        max_length=200,
                        verbose_name="GitHub repository",
                    ),
                ),
                (
                    "tag_prefix",
                    models.CharField(
                        default="v",
                        help_text="Git tags for this firmware start with this, e.g. “v” for v1.4.2, or “boot-v” for boot-v1.0.0. Published GitHub releases with a matching tag are added here automatically.",
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firmwares",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "name"],
                "unique_together": {("project", "slug")},
            },
        ),
        migrations.CreateModel(
            name="FirmwareRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Semantic version: MAJOR.MINOR.PATCH, e.g. 1.4.2 or 2.0.0-rc.1",
                        max_length=60,
                    ),
                ),
                (
                    "sort_key",
                    models.CharField(db_index=True, editable=False, max_length=120),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("testing", "Testing"),
                            ("released", "Released"),
                            ("deprecated", "Deprecated"),
                            ("recalled", "Recalled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "git_ref",
                    models.CharField(
                        blank=True,
                        help_text="The tag or commit this was built from, e.g. v1.4.2 or 3f9c2ab",
                        max_length=100,
                        verbose_name="Git tag or commit",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the GitHub release or CI run, if any.",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Release notes")),
                ("status_note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firmware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="firmware.firmware",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revisions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="firmware_releases",
                        to="projects.revision",
                        verbose_name="Compatible board revisions",
                    ),
                ),
            ],
            options={
                "ordering": ["firmware", "-sort_key"],
                "unique_together": {("firmware", "version")},
            },
        ),
        migrations.CreateModel(
            name="FirmwareArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=400, upload_to=apps.firmware.models.artifact_path
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image to flash"),
                            ("bootloader", "Bootloader"),
                            ("debug", "Debug symbols / map"),
                            ("package", "Update package"),
                            ("other", "Other"),
                        ],
                        default="image",
                        max_length=12,
                    ),
                ),
                ("size", models.BigIntegerField(default=0)),
                ("sha256", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="firmware.firmwarerelease",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "name"],
            },
        ),
    ]
