# Generated by Django 5.2.17 on 2026-09-29 15:29

from django.db import migrations, models


def recompute_sort_keys(apps, schema_editor):
    """Pre-release identifiers are now compared numerically (rc.2 < rc.10)."""
    from apps.firmware.models import parse_version, sort_key

    FirmwareRelease = apps.get_model("firmware", "FirmwareRelease")
    for rel in FirmwareRelease.objects.all().only("pk", "version"):
        if parse_version(rel.version):
            FirmwareRelease.objects.filter(pk=rel.pk).update(sort_key=sort_key(rel.version))


class Migration(migrations.Migration):

    dependencies = [
        ("firmware", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firmwarerelease",
            name="sort_key",
            field=models.CharField(db_index=True, editable=False, max_length=255),
        ),
        migrations.RunPython(recompute_sort_keys, migrations.RunPython.noop),
    ]
